from recipe_helper import R

RECIPES = [
    R(
        name="Paneer Butter Masala",
        name_hi="",
        region="North India",
        state="Delhi",
        cat="Main Course",
        veg=True,
        diff="Hard",
        prep=54,
        cook=32,
        serves=5,
        story="An authentic flavor from Delhi, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=546, pro=22, carb=40, fat=35
    ),
    R(
        name="Paneer Kadhai",
        name_hi="",
        region="North India",
        state="UP",
        cat="Main Course",
        veg=True,
        diff="Hard",
        prep=39,
        cook=64,
        serves=4,
        story="An authentic flavor from UP, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=467, pro=13, carb=38, fat=17
    ),
    R(
        name="Paneer Lababdar",
        name_hi="",
        region="North India",
        state="Delhi",
        cat="Main Course",
        veg=True,
        diff="Easy",
        prep=37,
        cook=75,
        serves=6,
        story="An authentic flavor from Delhi, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=358, pro=16, carb=22, fat=10
    ),
    R(
        name="Paneer Handi",
        name_hi="",
        region="North India",
        state="Kashmir",
        cat="Main Course",
        veg=True,
        diff="Hard",
        prep=27,
        cook=89,
        serves=5,
        story="An authentic flavor from Kashmir, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=316, pro=30, carb=43, fat=37
    ),
    R(
        name="Paneer Shahi",
        name_hi="",
        region="North India",
        state="Punjab",
        cat="Main Course",
        veg=True,
        diff="Medium",
        prep=49,
        cook=15,
        serves=6,
        story="An authentic flavor from Punjab, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=535, pro=19, carb=28, fat=36
    ),
    R(
        name="Paneer Korma",
        name_hi="",
        region="North India",
        state="Haryana",
        cat="Main Course",
        veg=True,
        diff="Medium",
        prep=31,
        cook=26,
        serves=3,
        story="An authentic flavor from Haryana, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=376, pro=12, carb=14, fat=36
    ),
    R(
        name="Paneer Makhani",
        name_hi="",
        region="North India",
        state="UP",
        cat="Main Course",
        veg=True,
        diff="Medium",
        prep=56,
        cook=30,
        serves=5,
        story="An authentic flavor from UP, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=493, pro=30, carb=14, fat=32
    ),
    R(
        name="Paneer Do Pyaza",
        name_hi="",
        region="North India",
        state="Haryana",
        cat="Main Course",
        veg=True,
        diff="Easy",
        prep=53,
        cook=18,
        serves=5,
        story="An authentic flavor from Haryana, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=437, pro=15, carb=38, fat=23
    ),
    R(
        name="Paneer Tikka Masala",
        name_hi="",
        region="North India",
        state="Himachal",
        cat="Main Course",
        veg=True,
        diff="Hard",
        prep=39,
        cook=19,
        serves=3,
        story="An authentic flavor from Himachal, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=321, pro=20, carb=37, fat=24
    ),
    R(
        name="Mushroom Butter Masala",
        name_hi="",
        region="North India",
        state="Himachal",
        cat="Main Course",
        veg=True,
        diff="Hard",
        prep=56,
        cook=63,
        serves=6,
        story="An authentic flavor from Himachal, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=451, pro=17, carb=26, fat=14
    ),
    R(
        name="Mushroom Kadhai",
        name_hi="",
        region="North India",
        state="UP",
        cat="Main Course",
        veg=True,
        diff="Medium",
        prep=14,
        cook=27,
        serves=4,
        story="An authentic flavor from UP, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=507, pro=8, carb=17, fat=10
    ),
    R(
        name="Mushroom Lababdar",
        name_hi="",
        region="North India",
        state="Haryana",
        cat="Main Course",
        veg=True,
        diff="Medium",
        prep=34,
        cook=19,
        serves=2,
        story="An authentic flavor from Haryana, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=579, pro=16, carb=15, fat=34
    ),
    R(
        name="Mushroom Handi",
        name_hi="",
        region="North India",
        state="UP",
        cat="Main Course",
        veg=True,
        diff="Hard",
        prep=54,
        cook=51,
        serves=5,
        story="An authentic flavor from UP, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=477, pro=20, carb=45, fat=34
    ),
    R(
        name="Mushroom Shahi",
        name_hi="",
        region="North India",
        state="Delhi",
        cat="Main Course",
        veg=True,
        diff="Hard",
        prep=20,
        cook=86,
        serves=6,
        story="An authentic flavor from Delhi, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=397, pro=26, carb=44, fat=39
    ),
    R(
        name="Mushroom Korma",
        name_hi="",
        region="North India",
        state="Himachal",
        cat="Main Course",
        veg=True,
        diff="Hard",
        prep=18,
        cook=76,
        serves=2,
        story="An authentic flavor from Himachal, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=461, pro=11, carb=45, fat=26
    ),
    R(
        name="Mushroom Makhani",
        name_hi="",
        region="North India",
        state="Punjab",
        cat="Main Course",
        veg=True,
        diff="Hard",
        prep=32,
        cook=66,
        serves=5,
        story="An authentic flavor from Punjab, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=419, pro=27, carb=23, fat=19
    ),
    R(
        name="Mushroom Do Pyaza",
        name_hi="",
        region="North India",
        state="Delhi",
        cat="Main Course",
        veg=True,
        diff="Hard",
        prep=18,
        cook=62,
        serves=6,
        story="An authentic flavor from Delhi, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=200, pro=21, carb=24, fat=31
    ),
    R(
        name="Mushroom Tikka Masala",
        name_hi="",
        region="North India",
        state="Himachal",
        cat="Main Course",
        veg=True,
        diff="Hard",
        prep=49,
        cook=29,
        serves=4,
        story="An authentic flavor from Himachal, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=495, pro=25, carb=19, fat=22
    ),
    R(
        name="Gobi Butter Masala",
        name_hi="",
        region="North India",
        state="Himachal",
        cat="Main Course",
        veg=True,
        diff="Easy",
        prep=38,
        cook=40,
        serves=2,
        story="An authentic flavor from Himachal, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=251, pro=27, carb=38, fat=35
    ),
    R(
        name="Gobi Kadhai",
        name_hi="",
        region="North India",
        state="Himachal",
        cat="Main Course",
        veg=True,
        diff="Hard",
        prep=24,
        cook=73,
        serves=6,
        story="An authentic flavor from Himachal, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=585, pro=23, carb=34, fat=17
    ),
    R(
        name="Gobi Lababdar",
        name_hi="",
        region="North India",
        state="Himachal",
        cat="Main Course",
        veg=True,
        diff="Hard",
        prep=28,
        cook=72,
        serves=3,
        story="An authentic flavor from Himachal, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=453, pro=23, carb=21, fat=14
    ),
    R(
        name="Gobi Handi",
        name_hi="",
        region="North India",
        state="Kashmir",
        cat="Main Course",
        veg=True,
        diff="Medium",
        prep=44,
        cook=31,
        serves=2,
        story="An authentic flavor from Kashmir, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=442, pro=27, carb=38, fat=28
    ),
    R(
        name="Gobi Shahi",
        name_hi="",
        region="North India",
        state="UP",
        cat="Main Course",
        veg=True,
        diff="Medium",
        prep=23,
        cook=35,
        serves=2,
        story="An authentic flavor from UP, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=272, pro=13, carb=42, fat=10
    ),
    R(
        name="Gobi Korma",
        name_hi="",
        region="North India",
        state="Haryana",
        cat="Main Course",
        veg=True,
        diff="Medium",
        prep=23,
        cook=24,
        serves=2,
        story="An authentic flavor from Haryana, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=541, pro=21, carb=42, fat=14
    ),
    R(
        name="Gobi Makhani",
        name_hi="",
        region="North India",
        state="Kashmir",
        cat="Main Course",
        veg=True,
        diff="Easy",
        prep=53,
        cook=48,
        serves=6,
        story="An authentic flavor from Kashmir, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=328, pro=29, carb=27, fat=22
    ),
    R(
        name="Gobi Do Pyaza",
        name_hi="",
        region="North India",
        state="Himachal",
        cat="Main Course",
        veg=True,
        diff="Hard",
        prep=37,
        cook=51,
        serves=2,
        story="An authentic flavor from Himachal, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=393, pro=18, carb=47, fat=39
    ),
    R(
        name="Gobi Tikka Masala",
        name_hi="",
        region="North India",
        state="Himachal",
        cat="Main Course",
        veg=True,
        diff="Hard",
        prep=43,
        cook=75,
        serves=5,
        story="An authentic flavor from Himachal, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=328, pro=10, carb=25, fat=24
    ),
    R(
        name="Aloo Butter Masala",
        name_hi="",
        region="North India",
        state="Haryana",
        cat="Main Course",
        veg=True,
        diff="Easy",
        prep=22,
        cook=44,
        serves=2,
        story="An authentic flavor from Haryana, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=506, pro=26, carb=42, fat=33
    ),
    R(
        name="Aloo Kadhai",
        name_hi="",
        region="North India",
        state="UP",
        cat="Main Course",
        veg=True,
        diff="Easy",
        prep=15,
        cook=38,
        serves=5,
        story="An authentic flavor from UP, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=357, pro=15, carb=19, fat=14
    ),
    R(
        name="Aloo Lababdar",
        name_hi="",
        region="North India",
        state="UP",
        cat="Main Course",
        veg=True,
        diff="Easy",
        prep=15,
        cook=34,
        serves=3,
        story="An authentic flavor from UP, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=582, pro=27, carb=49, fat=31
    ),
    R(
        name="Aloo Handi",
        name_hi="",
        region="North India",
        state="Kashmir",
        cat="Main Course",
        veg=True,
        diff="Medium",
        prep=57,
        cook=23,
        serves=3,
        story="An authentic flavor from Kashmir, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=338, pro=11, carb=25, fat=25
    ),
    R(
        name="Aloo Shahi",
        name_hi="",
        region="North India",
        state="Punjab",
        cat="Main Course",
        veg=True,
        diff="Hard",
        prep=17,
        cook=80,
        serves=4,
        story="An authentic flavor from Punjab, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=254, pro=7, carb=30, fat=35
    ),
    R(
        name="Aloo Korma",
        name_hi="",
        region="North India",
        state="Kashmir",
        cat="Main Course",
        veg=True,
        diff="Easy",
        prep=15,
        cook=80,
        serves=6,
        story="An authentic flavor from Kashmir, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=316, pro=21, carb=19, fat=18
    ),
    R(
        name="Aloo Makhani",
        name_hi="",
        region="North India",
        state="Kashmir",
        cat="Main Course",
        veg=True,
        diff="Hard",
        prep=33,
        cook=63,
        serves=4,
        story="An authentic flavor from Kashmir, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=429, pro=30, carb=36, fat=12
    ),
    R(
        name="Aloo Do Pyaza",
        name_hi="",
        region="North India",
        state="Kashmir",
        cat="Main Course",
        veg=True,
        diff="Medium",
        prep=37,
        cook=32,
        serves=2,
        story="An authentic flavor from Kashmir, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=244, pro=27, carb=38, fat=13
    ),
    R(
        name="Aloo Tikka Masala",
        name_hi="",
        region="North India",
        state="Punjab",
        cat="Main Course",
        veg=True,
        diff="Hard",
        prep=12,
        cook=51,
        serves=2,
        story="An authentic flavor from Punjab, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=239, pro=13, carb=37, fat=36
    ),
    R(
        name="Matar Butter Masala",
        name_hi="",
        region="North India",
        state="UP",
        cat="Main Course",
        veg=True,
        diff="Medium",
        prep=23,
        cook=57,
        serves=6,
        story="An authentic flavor from UP, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=395, pro=26, carb=14, fat=15
    ),
    R(
        name="Matar Kadhai",
        name_hi="",
        region="North India",
        state="UP",
        cat="Main Course",
        veg=True,
        diff="Easy",
        prep=40,
        cook=74,
        serves=3,
        story="An authentic flavor from UP, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=586, pro=29, carb=49, fat=22
    ),
    R(
        name="Matar Lababdar",
        name_hi="",
        region="North India",
        state="Haryana",
        cat="Main Course",
        veg=True,
        diff="Hard",
        prep=34,
        cook=47,
        serves=2,
        story="An authentic flavor from Haryana, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=389, pro=21, carb=12, fat=21
    ),
    R(
        name="Matar Handi",
        name_hi="",
        region="North India",
        state="Punjab",
        cat="Main Course",
        veg=True,
        diff="Medium",
        prep=38,
        cook=16,
        serves=2,
        story="An authentic flavor from Punjab, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=501, pro=25, carb=18, fat=33
    ),
    R(
        name="Matar Shahi",
        name_hi="",
        region="North India",
        state="UP",
        cat="Main Course",
        veg=True,
        diff="Easy",
        prep=26,
        cook=75,
        serves=6,
        story="An authentic flavor from UP, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=241, pro=28, carb=27, fat=23
    ),
    R(
        name="Matar Korma",
        name_hi="",
        region="North India",
        state="UP",
        cat="Main Course",
        veg=True,
        diff="Hard",
        prep=22,
        cook=55,
        serves=5,
        story="An authentic flavor from UP, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=299, pro=30, carb=32, fat=18
    ),
    R(
        name="Matar Makhani",
        name_hi="",
        region="North India",
        state="Himachal",
        cat="Main Course",
        veg=True,
        diff="Easy",
        prep=13,
        cook=21,
        serves=2,
        story="An authentic flavor from Himachal, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=560, pro=8, carb=50, fat=38
    ),
    R(
        name="Matar Do Pyaza",
        name_hi="",
        region="North India",
        state="Kashmir",
        cat="Main Course",
        veg=True,
        diff="Medium",
        prep=30,
        cook=78,
        serves=6,
        story="An authentic flavor from Kashmir, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=428, pro=18, carb=40, fat=25
    ),
    R(
        name="Matar Tikka Masala",
        name_hi="",
        region="North India",
        state="Haryana",
        cat="Main Course",
        veg=True,
        diff="Medium",
        prep=38,
        cook=26,
        serves=4,
        story="An authentic flavor from Haryana, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=246, pro=30, carb=48, fat=26
    ),
    R(
        name="Kofta Butter Masala",
        name_hi="",
        region="North India",
        state="Haryana",
        cat="Main Course",
        veg=True,
        diff="Medium",
        prep=19,
        cook=53,
        serves=3,
        story="An authentic flavor from Haryana, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=433, pro=5, carb=35, fat=24
    ),
    R(
        name="Kofta Kadhai",
        name_hi="",
        region="North India",
        state="Kashmir",
        cat="Main Course",
        veg=True,
        diff="Easy",
        prep=30,
        cook=51,
        serves=5,
        story="An authentic flavor from Kashmir, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=433, pro=23, carb=11, fat=21
    ),
    R(
        name="Kofta Lababdar",
        name_hi="",
        region="North India",
        state="Kashmir",
        cat="Main Course",
        veg=True,
        diff="Easy",
        prep=56,
        cook=21,
        serves=4,
        story="An authentic flavor from Kashmir, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=361, pro=21, carb=28, fat=34
    ),
    R(
        name="Kofta Handi",
        name_hi="",
        region="North India",
        state="UP",
        cat="Main Course",
        veg=True,
        diff="Hard",
        prep=48,
        cook=89,
        serves=2,
        story="An authentic flavor from UP, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=294, pro=26, carb=48, fat=15
    ),
    R(
        name="Kofta Shahi",
        name_hi="",
        region="North India",
        state="Haryana",
        cat="Main Course",
        veg=True,
        diff="Easy",
        prep=13,
        cook=37,
        serves=3,
        story="An authentic flavor from Haryana, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=558, pro=28, carb=36, fat=16
    ),
    R(
        name="Kofta Korma",
        name_hi="",
        region="North India",
        state="Himachal",
        cat="Main Course",
        veg=True,
        diff="Easy",
        prep=40,
        cook=57,
        serves=3,
        story="An authentic flavor from Himachal, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=573, pro=12, carb=38, fat=36
    ),
    R(
        name="Kofta Makhani",
        name_hi="",
        region="North India",
        state="Haryana",
        cat="Main Course",
        veg=True,
        diff="Hard",
        prep=34,
        cook=59,
        serves=2,
        story="An authentic flavor from Haryana, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=539, pro=27, carb=22, fat=34
    ),
    R(
        name="Kofta Do Pyaza",
        name_hi="",
        region="North India",
        state="Kashmir",
        cat="Main Course",
        veg=True,
        diff="Medium",
        prep=16,
        cook=70,
        serves=2,
        story="An authentic flavor from Kashmir, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=494, pro=30, carb=33, fat=24
    ),
    R(
        name="Kofta Tikka Masala",
        name_hi="",
        region="North India",
        state="Kashmir",
        cat="Main Course",
        veg=True,
        diff="Medium",
        prep=18,
        cook=60,
        serves=3,
        story="An authentic flavor from Kashmir, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=583, pro=8, carb=22, fat=19
    ),
    R(
        name="Dal Butter Masala",
        name_hi="",
        region="North India",
        state="Himachal",
        cat="Main Course",
        veg=True,
        diff="Medium",
        prep=30,
        cook=65,
        serves=4,
        story="An authentic flavor from Himachal, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=592, pro=5, carb=12, fat=33
    ),
    R(
        name="Dal Kadhai",
        name_hi="",
        region="North India",
        state="UP",
        cat="Main Course",
        veg=True,
        diff="Medium",
        prep=40,
        cook=73,
        serves=5,
        story="An authentic flavor from UP, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=595, pro=22, carb=25, fat=12
    ),
    R(
        name="Dal Lababdar",
        name_hi="",
        region="North India",
        state="UP",
        cat="Main Course",
        veg=True,
        diff="Medium",
        prep=22,
        cook=64,
        serves=6,
        story="An authentic flavor from UP, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=293, pro=5, carb=12, fat=11
    ),
    R(
        name="Dal Handi",
        name_hi="",
        region="North India",
        state="Himachal",
        cat="Main Course",
        veg=True,
        diff="Hard",
        prep=20,
        cook=60,
        serves=4,
        story="An authentic flavor from Himachal, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=237, pro=15, carb=13, fat=37
    ),
    R(
        name="Dal Shahi",
        name_hi="",
        region="North India",
        state="Delhi",
        cat="Main Course",
        veg=True,
        diff="Easy",
        prep=32,
        cook=59,
        serves=2,
        story="An authentic flavor from Delhi, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=523, pro=30, carb=40, fat=17
    ),
    R(
        name="Dal Korma",
        name_hi="",
        region="North India",
        state="Himachal",
        cat="Main Course",
        veg=True,
        diff="Easy",
        prep=21,
        cook=19,
        serves=5,
        story="An authentic flavor from Himachal, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=515, pro=19, carb=13, fat=27
    ),
    R(
        name="Dal Makhani",
        name_hi="",
        region="North India",
        state="Delhi",
        cat="Main Course",
        veg=True,
        diff="Medium",
        prep=56,
        cook=72,
        serves=2,
        story="An authentic flavor from Delhi, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=378, pro=28, carb=50, fat=32
    ),
    R(
        name="Dal Do Pyaza",
        name_hi="",
        region="North India",
        state="Himachal",
        cat="Main Course",
        veg=True,
        diff="Easy",
        prep=59,
        cook=65,
        serves=4,
        story="An authentic flavor from Himachal, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=439, pro=22, carb=40, fat=38
    ),
    R(
        name="Dal Tikka Masala",
        name_hi="",
        region="North India",
        state="Delhi",
        cat="Main Course",
        veg=True,
        diff="Hard",
        prep=55,
        cook=34,
        serves=2,
        story="An authentic flavor from Delhi, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=373, pro=8, carb=15, fat=18
    ),
    R(
        name="Chana Butter Masala",
        name_hi="",
        region="North India",
        state="UP",
        cat="Main Course",
        veg=True,
        diff="Medium",
        prep=27,
        cook=32,
        serves=5,
        story="An authentic flavor from UP, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=537, pro=5, carb=36, fat=29
    ),
    R(
        name="Chana Kadhai",
        name_hi="",
        region="North India",
        state="Haryana",
        cat="Main Course",
        veg=True,
        diff="Medium",
        prep=23,
        cook=60,
        serves=6,
        story="An authentic flavor from Haryana, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=558, pro=26, carb=36, fat=19
    ),
    R(
        name="Chana Lababdar",
        name_hi="",
        region="North India",
        state="Punjab",
        cat="Main Course",
        veg=True,
        diff="Medium",
        prep=19,
        cook=52,
        serves=2,
        story="An authentic flavor from Punjab, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=397, pro=17, carb=48, fat=25
    ),
    R(
        name="Chana Handi",
        name_hi="",
        region="North India",
        state="UP",
        cat="Main Course",
        veg=True,
        diff="Easy",
        prep=46,
        cook=52,
        serves=2,
        story="An authentic flavor from UP, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=401, pro=26, carb=27, fat=19
    ),
    R(
        name="Chana Shahi",
        name_hi="",
        region="North India",
        state="Himachal",
        cat="Main Course",
        veg=True,
        diff="Hard",
        prep=33,
        cook=77,
        serves=6,
        story="An authentic flavor from Himachal, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=575, pro=8, carb=44, fat=28
    ),
    R(
        name="Chana Korma",
        name_hi="",
        region="North India",
        state="Punjab",
        cat="Main Course",
        veg=True,
        diff="Easy",
        prep=36,
        cook=63,
        serves=4,
        story="An authentic flavor from Punjab, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=355, pro=20, carb=50, fat=37
    ),
    R(
        name="Chana Makhani",
        name_hi="",
        region="North India",
        state="Himachal",
        cat="Main Course",
        veg=True,
        diff="Medium",
        prep=59,
        cook=44,
        serves=3,
        story="An authentic flavor from Himachal, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=295, pro=8, carb=50, fat=23
    ),
    R(
        name="Chana Do Pyaza",
        name_hi="",
        region="North India",
        state="Kashmir",
        cat="Main Course",
        veg=True,
        diff="Medium",
        prep=13,
        cook=78,
        serves=3,
        story="An authentic flavor from Kashmir, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=234, pro=12, carb=38, fat=40
    ),
    R(
        name="Chana Tikka Masala",
        name_hi="",
        region="North India",
        state="UP",
        cat="Main Course",
        veg=True,
        diff="Medium",
        prep=58,
        cook=66,
        serves=5,
        story="An authentic flavor from UP, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=230, pro=27, carb=20, fat=22
    ),
    R(
        name="Rajma Butter Masala",
        name_hi="",
        region="North India",
        state="UP",
        cat="Main Course",
        veg=True,
        diff="Hard",
        prep=33,
        cook=38,
        serves=6,
        story="An authentic flavor from UP, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=301, pro=22, carb=24, fat=39
    ),
    R(
        name="Rajma Kadhai",
        name_hi="",
        region="North India",
        state="UP",
        cat="Main Course",
        veg=True,
        diff="Easy",
        prep=24,
        cook=22,
        serves=3,
        story="An authentic flavor from UP, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=400, pro=7, carb=29, fat=39
    ),
    R(
        name="Rajma Lababdar",
        name_hi="",
        region="North India",
        state="Himachal",
        cat="Main Course",
        veg=True,
        diff="Easy",
        prep=54,
        cook=84,
        serves=4,
        story="An authentic flavor from Himachal, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=250, pro=11, carb=41, fat=14
    ),
    R(
        name="Rajma Handi",
        name_hi="",
        region="North India",
        state="Punjab",
        cat="Main Course",
        veg=True,
        diff="Hard",
        prep=12,
        cook=22,
        serves=4,
        story="An authentic flavor from Punjab, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=480, pro=13, carb=37, fat=40
    ),
    R(
        name="Rajma Shahi",
        name_hi="",
        region="North India",
        state="Kashmir",
        cat="Main Course",
        veg=True,
        diff="Medium",
        prep=11,
        cook=56,
        serves=5,
        story="An authentic flavor from Kashmir, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=303, pro=25, carb=39, fat=12
    ),
    R(
        name="Rajma Korma",
        name_hi="",
        region="North India",
        state="Haryana",
        cat="Main Course",
        veg=True,
        diff="Hard",
        prep=60,
        cook=47,
        serves=3,
        story="An authentic flavor from Haryana, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=283, pro=29, carb=33, fat=35
    ),
    R(
        name="Rajma Makhani",
        name_hi="",
        region="North India",
        state="Haryana",
        cat="Main Course",
        veg=True,
        diff="Easy",
        prep=13,
        cook=40,
        serves=3,
        story="An authentic flavor from Haryana, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=591, pro=29, carb=12, fat=10
    ),
    R(
        name="Rajma Do Pyaza",
        name_hi="",
        region="North India",
        state="Delhi",
        cat="Main Course",
        veg=True,
        diff="Medium",
        prep=13,
        cook=66,
        serves=3,
        story="An authentic flavor from Delhi, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=567, pro=6, carb=11, fat=19
    ),
    R(
        name="Rajma Tikka Masala",
        name_hi="",
        region="North India",
        state="Kashmir",
        cat="Main Course",
        veg=True,
        diff="Easy",
        prep=44,
        cook=88,
        serves=2,
        story="An authentic flavor from Kashmir, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=557, pro=25, carb=27, fat=30
    ),
    R(
        name="Baingan Butter Masala",
        name_hi="",
        region="North India",
        state="Haryana",
        cat="Main Course",
        veg=True,
        diff="Easy",
        prep=33,
        cook=84,
        serves=4,
        story="An authentic flavor from Haryana, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=417, pro=24, carb=37, fat=27
    ),
    R(
        name="Baingan Kadhai",
        name_hi="",
        region="North India",
        state="Punjab",
        cat="Main Course",
        veg=True,
        diff="Hard",
        prep=10,
        cook=62,
        serves=6,
        story="An authentic flavor from Punjab, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=452, pro=23, carb=38, fat=36
    ),
    R(
        name="Baingan Lababdar",
        name_hi="",
        region="North India",
        state="Delhi",
        cat="Main Course",
        veg=True,
        diff="Medium",
        prep=48,
        cook=64,
        serves=6,
        story="An authentic flavor from Delhi, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=435, pro=27, carb=26, fat=14
    ),
    R(
        name="Baingan Handi",
        name_hi="",
        region="North India",
        state="Delhi",
        cat="Main Course",
        veg=True,
        diff="Hard",
        prep=43,
        cook=26,
        serves=6,
        story="An authentic flavor from Delhi, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=277, pro=18, carb=32, fat=40
    ),
    R(
        name="Baingan Shahi",
        name_hi="",
        region="North India",
        state="Himachal",
        cat="Main Course",
        veg=True,
        diff="Easy",
        prep=46,
        cook=17,
        serves=3,
        story="An authentic flavor from Himachal, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=307, pro=26, carb=42, fat=25
    ),
    R(
        name="Baingan Korma",
        name_hi="",
        region="North India",
        state="UP",
        cat="Main Course",
        veg=True,
        diff="Easy",
        prep=26,
        cook=28,
        serves=2,
        story="An authentic flavor from UP, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=325, pro=7, carb=24, fat=22
    ),
    R(
        name="Baingan Makhani",
        name_hi="",
        region="North India",
        state="Punjab",
        cat="Main Course",
        veg=True,
        diff="Medium",
        prep=21,
        cook=26,
        serves=3,
        story="An authentic flavor from Punjab, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=597, pro=30, carb=17, fat=21
    ),
    R(
        name="Baingan Do Pyaza",
        name_hi="",
        region="North India",
        state="Himachal",
        cat="Main Course",
        veg=True,
        diff="Easy",
        prep=33,
        cook=54,
        serves=4,
        story="An authentic flavor from Himachal, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=408, pro=20, carb=14, fat=17
    ),
    R(
        name="Baingan Tikka Masala",
        name_hi="",
        region="North India",
        state="Himachal",
        cat="Main Course",
        veg=True,
        diff="Hard",
        prep=43,
        cook=73,
        serves=4,
        story="An authentic flavor from Himachal, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=543, pro=30, carb=41, fat=12
    ),
    R(
        name="Bhindi Butter Masala",
        name_hi="",
        region="North India",
        state="Kashmir",
        cat="Main Course",
        veg=True,
        diff="Medium",
        prep=39,
        cook=55,
        serves=4,
        story="An authentic flavor from Kashmir, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=205, pro=24, carb=32, fat=17
    ),
    R(
        name="Bhindi Kadhai",
        name_hi="",
        region="North India",
        state="Punjab",
        cat="Main Course",
        veg=True,
        diff="Medium",
        prep=17,
        cook=42,
        serves=2,
        story="An authentic flavor from Punjab, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=537, pro=25, carb=39, fat=37
    ),
    R(
        name="Bhindi Lababdar",
        name_hi="",
        region="North India",
        state="Kashmir",
        cat="Main Course",
        veg=True,
        diff="Hard",
        prep=33,
        cook=52,
        serves=2,
        story="An authentic flavor from Kashmir, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=397, pro=27, carb=48, fat=27
    ),
    R(
        name="Bhindi Handi",
        name_hi="",
        region="North India",
        state="Haryana",
        cat="Main Course",
        veg=True,
        diff="Easy",
        prep=44,
        cook=55,
        serves=3,
        story="An authentic flavor from Haryana, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=482, pro=25, carb=22, fat=15
    ),
    R(
        name="Bhindi Shahi",
        name_hi="",
        region="North India",
        state="Punjab",
        cat="Main Course",
        veg=True,
        diff="Medium",
        prep=17,
        cook=77,
        serves=3,
        story="An authentic flavor from Punjab, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=536, pro=10, carb=37, fat=28
    ),
    R(
        name="Bhindi Korma",
        name_hi="",
        region="North India",
        state="Delhi",
        cat="Main Course",
        veg=True,
        diff="Hard",
        prep=56,
        cook=55,
        serves=2,
        story="An authentic flavor from Delhi, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=275, pro=9, carb=28, fat=22
    ),
    R(
        name="Bhindi Makhani",
        name_hi="",
        region="North India",
        state="Himachal",
        cat="Main Course",
        veg=True,
        diff="Easy",
        prep=26,
        cook=18,
        serves=4,
        story="An authentic flavor from Himachal, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=240, pro=30, carb=22, fat=10
    ),
    R(
        name="Bhindi Do Pyaza",
        name_hi="",
        region="North India",
        state="Himachal",
        cat="Main Course",
        veg=True,
        diff="Medium",
        prep=47,
        cook=67,
        serves=5,
        story="An authentic flavor from Himachal, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=255, pro=11, carb=15, fat=39
    ),
    R(
        name="Bhindi Tikka Masala",
        name_hi="",
        region="North India",
        state="Haryana",
        cat="Main Course",
        veg=True,
        diff="Hard",
        prep=32,
        cook=89,
        serves=2,
        story="An authentic flavor from Haryana, North India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=303, pro=17, carb=23, fat=21
    )
]
