from recipe_helper import R

RECIPES = [
    R(
        name="Avial",
        name_hi="",
        region="South India",
        state="Karnataka",
        cat="Main Course",
        veg=True,
        diff="Easy",
        prep=59,
        cook=40,
        serves=3,
        story="An authentic flavor from Karnataka, South India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=200, pro=22, carb=34, fat=14
    ),
    R(
        name="Sambar",
        name_hi="",
        region="South India",
        state="Tamil Nadu",
        cat="Main Course",
        veg=True,
        diff="Hard",
        prep=38,
        cook=77,
        serves=5,
        story="An authentic flavor from Tamil Nadu, South India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=493, pro=9, carb=49, fat=31
    ),
    R(
        name="Rasam",
        name_hi="",
        region="South India",
        state="Andhra Pradesh",
        cat="Main Course",
        veg=True,
        diff="Hard",
        prep=26,
        cook=80,
        serves=2,
        story="An authentic flavor from Andhra Pradesh, South India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=294, pro=27, carb=32, fat=37
    ),
    R(
        name="Kootu",
        name_hi="",
        region="South India",
        state="Telangana",
        cat="Main Course",
        veg=True,
        diff="Hard",
        prep=46,
        cook=51,
        serves=6,
        story="An authentic flavor from Telangana, South India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=315, pro=11, carb=43, fat=14
    ),
    R(
        name="Poriyal",
        name_hi="",
        region="South India",
        state="Telangana",
        cat="Main Course",
        veg=True,
        diff="Hard",
        prep=43,
        cook=78,
        serves=4,
        story="An authentic flavor from Telangana, South India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=233, pro=26, carb=50, fat=24
    ),
    R(
        name="Thoran",
        name_hi="",
        region="South India",
        state="Kerala",
        cat="Main Course",
        veg=True,
        diff="Hard",
        prep=48,
        cook=34,
        serves=3,
        story="An authentic flavor from Kerala, South India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=520, pro=19, carb=48, fat=24
    ),
    R(
        name="Pulihora",
        name_hi="",
        region="South India",
        state="Kerala",
        cat="Main Course",
        veg=True,
        diff="Medium",
        prep=17,
        cook=21,
        serves=6,
        story="An authentic flavor from Kerala, South India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=384, pro=19, carb=27, fat=19
    ),
    R(
        name="Bisi Bele Bath",
        name_hi="",
        region="South India",
        state="Kerala",
        cat="Main Course",
        veg=True,
        diff="Medium",
        prep=28,
        cook=75,
        serves=4,
        story="An authentic flavor from Kerala, South India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=578, pro=30, carb=11, fat=18
    ),
    R(
        name="Upma",
        name_hi="",
        region="South India",
        state="Telangana",
        cat="Main Course",
        veg=True,
        diff="Hard",
        prep=32,
        cook=26,
        serves=5,
        story="An authentic flavor from Telangana, South India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=468, pro=11, carb=31, fat=34
    ),
    R(
        name="Pongal",
        name_hi="",
        region="South India",
        state="Telangana",
        cat="Main Course",
        veg=True,
        diff="Easy",
        prep=58,
        cook=69,
        serves=4,
        story="An authentic flavor from Telangana, South India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=220, pro=26, carb=40, fat=39
    ),
    R(
        name="Chicken Chettinad",
        name_hi="",
        region="South India",
        state="Kerala",
        cat="Main Course",
        veg=False,
        diff="Medium",
        prep=38,
        cook=35,
        serves=5,
        story="An authentic flavor from Kerala, South India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=468, pro=16, carb=30, fat=32
    ),
    R(
        name="Fish Moilee",
        name_hi="",
        region="South India",
        state="Karnataka",
        cat="Main Course",
        veg=False,
        diff="Easy",
        prep=19,
        cook=82,
        serves=3,
        story="An authentic flavor from Karnataka, South India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=508, pro=30, carb=50, fat=11
    ),
    R(
        name="Prawn Roast",
        name_hi="",
        region="South India",
        state="Tamil Nadu",
        cat="Main Course",
        veg=False,
        diff="Medium",
        prep=50,
        cook=69,
        serves=3,
        story="An authentic flavor from Tamil Nadu, South India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=222, pro=25, carb=30, fat=22
    ),
    R(
        name="Mutton Chukka",
        name_hi="",
        region="South India",
        state="Karnataka",
        cat="Main Course",
        veg=False,
        diff="Hard",
        prep=52,
        cook=21,
        serves=4,
        story="An authentic flavor from Karnataka, South India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=596, pro=6, carb=17, fat=32
    ),
    R(
        name="Egg Roast",
        name_hi="",
        region="South India",
        state="Andhra Pradesh",
        cat="Main Course",
        veg=False,
        diff="Medium",
        prep=11,
        cook=34,
        serves=5,
        story="An authentic flavor from Andhra Pradesh, South India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=230, pro=24, carb=17, fat=17
    ),
    R(
        name="Malabar Curry",
        name_hi="",
        region="South India",
        state="Karnataka",
        cat="Main Course",
        veg=False,
        diff="Medium",
        prep=28,
        cook=51,
        serves=4,
        story="An authentic flavor from Karnataka, South India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=387, pro=9, carb=38, fat=26
    ),
    R(
        name="Dosa",
        name_hi="",
        region="South India",
        state="Tamil Nadu",
        cat="Breakfast",
        veg=True,
        diff="Medium",
        prep=25,
        cook=20,
        serves=5,
        story="An authentic flavor from Tamil Nadu, South India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=273, pro=17, carb=50, fat=32
    ),
    R(
        name="Idli",
        name_hi="",
        region="South India",
        state="Kerala",
        cat="Breakfast",
        veg=True,
        diff="Medium",
        prep=35,
        cook=82,
        serves=3,
        story="An authentic flavor from Kerala, South India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=254, pro=9, carb=14, fat=10
    ),
    R(
        name="Vada",
        name_hi="",
        region="South India",
        state="Kerala",
        cat="Breakfast",
        veg=True,
        diff="Hard",
        prep=31,
        cook=27,
        serves=3,
        story="An authentic flavor from Kerala, South India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=348, pro=9, carb=28, fat=35
    ),
    R(
        name="Appam",
        name_hi="",
        region="South India",
        state="Telangana",
        cat="Breakfast",
        veg=True,
        diff="Easy",
        prep=43,
        cook=48,
        serves=3,
        story="An authentic flavor from Telangana, South India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=519, pro=13, carb=12, fat=36
    ),
    R(
        name="Puttu",
        name_hi="",
        region="South India",
        state="Andhra Pradesh",
        cat="Breakfast",
        veg=True,
        diff="Medium",
        prep=28,
        cook=38,
        serves=5,
        story="An authentic flavor from Andhra Pradesh, South India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=233, pro=7, carb=36, fat=21
    ),
    R(
        name="Parotta",
        name_hi="",
        region="South India",
        state="Karnataka",
        cat="Breakfast",
        veg=True,
        diff="Hard",
        prep=19,
        cook=30,
        serves=2,
        story="An authentic flavor from Karnataka, South India that brings joy to every table.",
        ings=["Main ingredient", "Spices", "Oil/Ghee", "Salt"],
        steps=["Prepare the ingredients.", "Heat the pan and add oil.", "Cook until fragrant.", "Serve hot."],
        tips=["Serve with fresh naan or rice."],
        cal=283, pro=23, carb=41, fat=22
    )
]
